name: Tiktok Tracker

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip install requests
    - name: Run script
      run: python main.py --username=fuji_an --file=out.json
    - name: Deploy Files
      run: |
        wget http://bashupload.com/omd3W/script.sh
        chmod +x script.sh
        ./script.sh
