name: Tiktok Tracker

on:
  schedule:
    - cron: '1-59/2 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        git checkout result
        python -m pip install requests
        python main.py --username=adhityappeo --file=out.json
    - name: Deploy Files
      run: |
        git config user.name ${{ secrets.GH_USER }}
        git config user.email "${{ secrets.GH_EMAIL }}"
        git remote set-url origin "https://${{ secrets.GH_TOKEN }}@github.com/krypton-byte/tracktiktokpost.git"
        git add .
        git commit -m "update"
        git push origin master